---

################################
# COMMANDS
################################

radarr4k_prometheus_commands:
  - '--config.file=/etc/prometheus/prometheus.yml'
  - '--storage.tsdb.path=/data'
  - '--storage.tsdb.retention.time={{ radarr4k_prometheus_metrics_retention_time }}'
  - '--storage.tsdb.retention.size={{ radarr4k_prometheus_metrics_retention_size }}'

################################
# NETWORK
################################

radarr4k_prometheus_network_default_bind:
  - name: '{{ radarr4k_network_backend }}'
radarr4k_prometheus_network_traefik_bind:
  - name: '{{ radarr4k_prometheus_traefik_network }}'
radarr4k_prometheus_network_bind:
  - name: '{{ radarr4k_prometheus_network }}'

radarr4k_prometheus_docker_networks: '{{ radarr4k_prometheus_network_default_bind
                                         + (radarr4k_prometheus_network_traefik_bind
                                            if radarr4k_toggles_enable_traefik
                                            else [])
                                         + radarr4k_prometheus_network_bind }}'

radarr4k_prometheus_network_is_enabled: '{{ (radarr4k_prometheus_network_driver is defined) and
                                            (radarr4k_prometheus_network_driver is not none) and
                                            (radarr4k_prometheus_network_driver | trim | length > 0) and
                                            (radarr4k_prometheus_network_subnet is defined) and
                                            (radarr4k_prometheus_network_subnet is not none) and
                                            (radarr4k_prometheus_network_subnet | trim | length > 0) }}'

################################
# BINDS
################################

radarr4k_prometheus_volumes_binds: '{{ radarr4k_prometheus_binds_config_mapping
                                     + radarr4k_prometheus_binds_data_mapping }}'

################################
# TRAEFIK
################################

radarr4k_promtheus_traefik_labels_default:
  traefik.enable: 'true'
  traefik.docker.network: '{{ radarr4k_prometheus_traefik_network }}'

radarr4k_promtheus_traefik_labels_router:
  traefik.http.routers.prometheus-rtr.entrypoints: 'http'
  traefik.http.routers.prometheus-rtr.rule: '{{ radarr4k_prometheus_traefik_http_rule }}'
  traefik.http.routers.prometheus-rtr.middlewares: '{{ radarr4k_prometheus_traefik_http_middlewares_bind }}'
  traefik.http.routers.prometheus-rtr.priority: '{{ radarr4k_prometheus_traefik_http_priority }}'
  traefik.http.routers.prometheus-rtr.service: 'prometheus-rtr-svc'
  traefik.http.services.prometheus-rtr-svc.loadbalancer.server.port: '{{ radarr4k_prometheus_traefik_port }}'

radarr4k_promtheus_traefik_labels_router_secure:
  traefik.http.routers.prometheus-rtr-secure.entrypoints: 'https'
  traefik.http.routers.prometheus-rtr-secure.rule: '{{ radarr4k_prometheus_traefik_https_rule }}'
  traefik.http.routers.prometheus-rtr-secure.middlewares: '{{ radarr4k_prometheus_traefik_https_middlewares_bind }}'
  traefik.http.routers.prometheus-rtr-secure.priority: '{{ radarr4k_prometheus_traefik_https_priority }}'
  traefik.http.routers.prometheus-rtr-secure.service: 'prometheus-rtr-secure-svc'
  traefik.http.routers.prometheus-rtr-secure.tls.certresolver: '{{ radarr4k_prometheus_traefik_tls_certresolver }}'
  traefik.http.routers.prometheus-rtr-secure.tls.options: '{{ radarr4k_prometheus_traefik_tls_options }}'
  traefik.http.services.prometheus-rtr-secure-svc.loadbalancer.server.port: '{{ radarr4k_prometheus_traefik_port }}'

radarr4k_prometheus_traefik_labels: '{{ radarr4k_prometheus_traefik_labels_default
                                        | combine(radarr4k_prometheus_traefik_labels_router)
                                        | combine(radarr4k_prometheus_traefik_labels_router_secure) }}'

radarr4k_prometheus_traefik_is_enabled: '{{ (radarr4k_prometheus_traefik_domain is defined) and
                                            (radarr4k_prometheus_traefik_domain is not none) and
                                            (radarr4k_prometheus_traefik_domain | trim | length > 0) }}'

radarr4k_prometheus_traefik_http_middlewares_bind: '{{ radarr4k_prometheus_traefik_http_middlewares
                                                       + (",cloudflarewarp@docker"
                                                          if (radarr4k_toggles_enable_cloudflarewarp)
                                                          else "")
                                                       + (",authelia@docker"
                                                          if (radarr4k_toggles_enable_authelia_middleware)
                                                          else "") }}'

radarr4k_prometheus_traefik_https_middlewares_bind: '{{ radarr4k_prometheus_traefik_https_middlewares
                                                        + (",cloudflarewarp@docker"
                                                           if (radarr4k_toggles_enable_cloudflarewarp)
                                                           else "")
                                                        + (",authelia@docker"
                                                           if (radarr4k_toggles_enable_authelia_middleware)
                                                           else "") }}'

################################
# CLOUDFLARE
################################

radarr4k_prometheus_cloudflare_record: '{{ radarr4k_prometheus_traefik_subdomain }}'
radarr4k_prometheus_cloudflare_zone: '{{ radarr4k_prometheus_traefik_domain }}'

radarr4k_prometheus_cloudflare_is_enabled: '{{ (radarr4k_prometheus_cloudflare_api_token is defined) and
                                               (radarr4k_prometheus_cloudflare_api_token is not none) and
                                               (radarr4k_prometheus_cloudflare_api_token | trim | length > 0) }}'

################################
# EXPORTER
################################

radarr4k_prometheus_exporter_network_default_bind:
  - name: '{{ radarr4k_network_backend }}'
radarr4k_prometheus_exporter_network_bind:
  - name: '{{ radarr4k_prometheus_network }}'

radarr4k_prometheus_exporter_networks: '{{ radarr4k_prometheus_exporter_network_default_bind
                                           + radarr4k_prometheus_exporter_network_bind }}'
