---

- name: Check for existing postgres databases
  block:
    - name: Ping for existing main database
      community.postgresql.postgresql_ping:
        login_host: '{{ radarr4k_postgres_basics_host }}'
        login_user: '{{ radarr4k_postgres_auth_user }}'
        login_password: '{{ radarr4k_postgres_auth_password }}'
        port: '{{ radarr4k_postgres_ports_host }}'
        db: '{{ radarr4k_postgres_database_main }}'
      register: radarr4k_postgres_maindb

    - name: Ping for existing log database
      community.postgresql.postgresql_ping:
        login_host: '{{ radarr4k_postgres_basics_host }}'
        login_user: '{{ radarr4k_postgres_auth_user }}'
        login_password: '{{ radarr4k_postgres_auth_password }}'
        port: '{{ radarr4k_postgres_ports_host }}'
        db: '{{ radarr4k_postgres_database_log }}'
      register: radarr4k_postgres_logdb

- name: Create postgres databases
  block:
    - name: Create postgres main database
      when: not radarr4k_postgres_maindb == true
      community.postgresql.postgresql_db:
        login_host: '{{ radarr4k_postgres_basics_host }}'
        login_user: '{{ radarr4k_postgres_auth_user }}'
        login_password: '{{ radarr4k_postgres_auth_password }}'
        port: '{{ radarr4k_postgres_ports_host }}'
        name: '{{ radarr4k_postgres_database_main }}'
        state: 'present'

    - name: Create postgres log database
      when: not radarr4k_postgres_logdb == true
      community.postgresql.postgresql_db:
        login_host: '{{ radarr4k_postgres_basics_host }}'
        login_user: '{{ radarr4k_postgres_auth_user }}'
        login_password: '{{ radarr4k_postgres_auth_password }}'
        port: '{{ radarr4k_postgres_ports_host }}'
        name: '{{ radarr4k_postgres_database_log }}'
        state: 'present'
