---

################################
# radarr4k
################################

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ radarr4k_cloudflare_api_token }}'
    zone: '{{ radarr4k_cloudflare_zone }}'
    state: absent
    type: CNAME
    record: '{{ radarr4k_cloudflare_record }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ radarr4k_cloudflare_api_token }}'
    zone: '{{ radarr4k_cloudflare_zone }}'
    state: absent
    type: A
    record: '{{ radarr4k_cloudflare_record }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      delegate_to: localhost
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add radarr4k DNS record
  community.general.cloudflare_dns:
    api_token: '{{ radarr4k_cloudflare_api_token }}'
    zone: '{{ radarr4k_cloudflare_zone }}'
    state: present
    solo: true
    proxied: '{{ radarr4k_cloudflare_proxy }}'
    type: '{{ radarr4k_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ radarr4k_cloudflare_record }}'
  register: radarr4k_cloudflare_record_creation_status

- name: Tasks on success
  when: radarr4k_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        radarr4k_cloudflare_record_print: '{{ (radarr4k_cloudflare_record == radarr4k_cloudflare_zone) | ternary(radarr4k_cloudflare_zone, radarr4k_cloudflare_record + "." + radarr4k_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ radarr4k_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ radarr4k_cloudflare_proxy }}'
