---

- name: Apply radarr4k-exporter prometheus scrape config
  ansible.builtin.blockinfile:
    path: '{{ radarr4k_prometheus_paths_location }}/prometheus.yml'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - RADARR4K-EXPORTER #"
    block: |
      {% filter indent(width=2, first=true) %}
      - job_name: '{{ radarr4k_prometheus_exporter_name }}'
        scrape_interval: 1m
        static_configs:
          - targets: ['{{ radarr4k_prometheus_exporter_name }}:{{ radarr4k_prometheus_exporter_cont_port }}']
      {% endfilter %}
  notify:
    - restart prometheus

- name: Create radarr4k prometheus exporter container
  community.docker.docker_container:
    name: '{{ radarr4k_prometheus_exporter_name }}'
    image: '{{ radarr4k_prometheus_exporter_image_repo }}:{{ radarr4k_prometheus_exporter_image_tag }}'
    command: ["radarr"]
    networks: '{{ radarr4k_prometheus_exporter_networks }}'
    env:
      PUID: '{{ radarr4k_prometheus_exporter_env_puid }}'
      PGID: '{{ radarr4k_prometheus_exporter_env_pgid }}'
      TZ: '{{ radarr4k_prometheus_exporter_env_timezone }}'
      PORT: '{{ radarr4k_prometheus_exporter_cont_port }}'
      URL: 'http://{{ radarr4k_basics_name }}:{{ radarr4k_ports_cont }}'
      API_KEY: '{{ radarr4k_api_key }}'
      ENABLE_ADDITIONAL_METRICS: 'true'
    ports:
      - '{{ radarr4k_prometheus_exporter_host_port }}:{{ radarr4k_prometheus_exporter_cont_port }}'
    restart_policy: '{{ radarr4k_prometheus_exporter_restart_policy }}'
